repos:
- hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
    exclude: ^.idea/
  - id: check-json
  - id: end-of-file-fixer
    exclude: ^.idea/
  - id: check-added-large-files
    args: ['--maxkb=10000']
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - files: requirements.txt
    id: python-safety-dependencies-check
  repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.1
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.3.0
- hooks:
  - id: hadolint-docker
  repo: https://github.com/hadolint/hadolint
  rev: v1.22.1
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.14.2
