version: '3'
tasks:
  push:
    - docker-compose push web
  pull:
    - docker-compose pull web
  restart-caddy:
    - docker-compose restart caddy
  stop-all:
    - docker-compose -f docker-compose.yml stop
  compile-dep:
    cmds:
      - docker-compose up compile-dep
  migrate:
    cmds:
      - docker-compose exec web ./manage.py migrate
  collectstatic:
    cmds:
      - docker-compose exec web ./manage.py collectstatic --noinput

  reset:
    cmds:
      - docker-compose -f docker-compose.yml down
      - docker volume rm quiz_app-dev_postgres
    ignore_error: true

  up:
    cmds:
      - docker-compose -f docker-compose.yml up -d
  init-app:
    desc: init or reset all the stack
    cmds:
      - task: reset
      - cmd: docker-compose -f docker-compose.yml pull
        ignore_error: true
      - task: up
      - task: migrate
      - task: collectstatic
