# Generated by Django 3.1.6 on 2021-02-08 19:27

from django.db import migrations
from django.conf import settings


def set_site_name(apps, name, domain):
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        pk=settings.SITE_ID, defaults={"name": name, "domain": domain}
    )


def set_personnalised_site_name(apps, schema_editor):
    set_site_name(apps, settings.SITE_NAME, settings.SITE_DOMAIN)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(set_personnalised_site_name, migrations.RunPython.noop),
    ]
